(monitor/report-definitions 
    (
        (
            (name . "temp_fluid_air") 
            (report-definition "volume-average" 
                (field . "temperature") 
                (old-props field "temperature" per-zone? #f average-over 1 zone-list (112) expr-list () zone-names (fluid_air) cff-field? #f phase "mixture" header "" retain-instantaneous-values? #f name "temp_fluid_air" type "volume-average") 
                (zone-list 112) 
                (expr-list) 
                (zone-names fluid_air) 
                (location-ids) 
                (locations (physics) (geometry) (surfaces)) 
                (per-zone? . #f) 
                (average-over . 1) 
                (phase . "mixture") 
                (report-type . "") 
                (retain-instantaneous-values? . #f)
            )
        ) 
        (
            (name . "temp_fluid_oil") 
            (report-definition "volume-average" 
                (field . "temperature") 
                (old-props field "temperature" per-zone? #f average-over 1 zone-list (107) expr-list () zone-names (fluid_oil) cff-field? #f phase "mixture" header "" retain-instantaneous-values? #f name "temp_fluid_oil" type "volume-average") 
                (zone-list 107) 
                (expr-list) 
                (zone-names fluid_oil) 
                (location-ids) 
                (locations (physics) (geometry) (surfaces)) 
                (per-zone? . #f) 
                (average-over . 1) 
                (phase . "mixture") 
                (report-type . "") 
                (retain-instantaneous-values? . #f)
            )
        ) 
        (
            (name . "outlet_temp") 
            (report-definition "surface-massavg" 
                (field . "temperature") 
                (old-props field "temperature" per-surface? #f average-over 1 surface-ids (6) location-type (2) surface-names (outlet) cff-field? #f phase "mixture" header "" retain-instantaneous-values? #f name "outlet_temp" type "surface-massavg") 
                (surface-ids 6) 
                (surface-names outlet) 
                (location-ids) 
                (locations (physics) (geometry) (surfaces)) 
                (per-surface? . #f) 
                (average-over . 1) 
                (phase . "mixture") 
                (report-type . "") 
                (retain-instantaneous-values? . #f)
            )
        ) 
        (
            (name . "outlet_air_temp") 
            (report-definition "surface-massavg" 
                (field . "temperature") 
                (old-props field "temperature" per-surface? #f average-over 1 surface-ids (3) location-type (2) surface-names (outlet_air) cff-field? #f phase "mixture" header "" retain-instantaneous-values? #f name "outlet_air_temp" type "surface-massavg") 
                (surface-ids 3) 
                (surface-names outlet_air) 
                (location-ids) 
                (locations (physics) (geometry) (surfaces)) 
                (per-surface? . #f) 
                (average-over . 1) 
                (phase . "mixture") 
                (report-type . "") 
                (retain-instantaneous-values? . #f)
            )
        ) 
        (
            (name . "lv_heat") 
            (report-definition "flux-heattransfer" 
                (zone-ids 39) 
                (zone-names "wall.1") 
                (location-ids) 
                (locations (physics) (geometry) (surfaces)) 
                (old-props per-zone? #f average-over 1 zone-ids (39) location-type (2) zone-names ("wall.1") phase "mixture" ids-for-net (39) header "" retain-instantaneous-values? #f name "lv_heat" type "flux-heattransfer") 
                (per-zone? . #f) 
                (average-over . 1) 
                (phase . "mixture") 
                (report-type . "") 
                (retain-instantaneous-values? . #f)
            )
        ) 
        (
            (name . "outlet_tempurature") 
            (report-definition "surface-massavg" 
                (field . "temperature") 
                (old-props field "temperature" per-surface? #f average-over 1 surface-ids (6) location-type (2) surface-names (outlet) cff-field? #f phase "mixture" header "" retain-instantaneous-values? #f name "outlet_tempurature" type "surface-massavg") 
                (surface-ids 6) 
                (surface-names outlet) 
                (location-ids) 
                (locations (physics) (geometry) (surfaces)) 
                (per-surface? . #f) 
                (average-over . 1) 
                (phase . "mixture") 
                (report-type . "") 
                (retain-instantaneous-values? . #f)
            )
        ) 
        (
            (name . "total-heat-transfer") 
            (report-definition surface-massavg 
                (field . "heat-flux") 
                (old-props field "heat-flux" per-surface? #f average-over 1 surface-ids (7 6 2) location-type (2 2 2) surface-names (inlet outlet wall.1) cff-field? #f phase "mixture" header "" retain-instantaneous-values? #f name "total-heat-transfer" type "surface-massavg") 
                (surface-ids 7 6 2) 
                (surface-names inlet outlet wall.1) 
                (location-ids) 
                (locations (physics) (geometry) (surfaces)) 
                (per-surface? . #f) 
                (average-over . 1) 
                (phase . "mixture") 
                (report-type . "") 
                (retain-instantaneous-values? . #f)
            )
        ) 
        (
            (name . "total heat trans") 
            (report-definition flux-heattransfer 
                (zone-ids 34 35 39) 
                (zone-names inlet outlet wall.1) 
                (location-ids) 
                (locations (physics) (geometry) (surfaces)) 
                (old-props per-zone? #f average-over 1 zone-ids (34 35 39) location-type (2 2 2) zone-names (inlet outlet wall.1) phase "mixture" ids-for-net (34 35 39) header "" retain-instantaneous-values? #f name "total heat trans" type "flux-heattransfer") 
                (per-zone? . #f) 
                (average-over . 1) 
                (phase . "mixture") 
                (report-type . "") 
                (retain-instantaneous-values? . #f)
            )
        )
    )
)
