(graphics/pathlines 
    (
        (
            (name . "pathlines-1") 
            (uid . "uid-1") 
            (velocity-domain . "all-phases") 
            (field . "Time") 
            (surfaces-list 6 7 8) 
            (location-ids) 
            (from-location (physics) (geometry) (surfaces)) 
            (range auto-range) 
            (range-options 
                (auto-range? . #f) 
                (minimum . 0.) 
                (maximum . 0.) 
                (compute . #f)
            ) 
            (style-attribute 
                (style . "line") 
                (line-width . 1) 
                (arrow-space . 1) 
                (arrow-scale . 1) 
                (marker-size . 0.1) 
                (sphere-size . 0.001128521854877472) 
                (sphere-lod . 8) 
                (radius . 0.001128521854877472) 
                (ribbon 
                    (field . "pressure") 
                    (scalefactor . 0.1)
                )
            ) 
            (style-attributes 
                (style . "line") 
                (line-width . 0.) 
                (space-factor . 0.) 
                (scale . 0.) 
                (width . 0.) 
                (marker-size . 0.) 
                (sphere-size . 0.) 
                (sphere-detail-lod . 0.) 
                (constant . #f) 
                (diameter . 0.) 
                (size-by . "") 
                (sphere-scale . 0.) 
                (sphere-lod . 0.) 
                (field . "") 
                (scale-factor . 0.) 
                (range-sphere 
                    (auto-range? . #f) 
                    (minimum . 0.) 
                    (maximum . 0.) 
                    (compute . #f)
                ) 
                (range-ribbon 
                    (minimum . 0.) 
                    (maximun . 0.) 
                    (compute . #f)
                )
            ) 
            (options 
                (oil-flow . #f) 
                (reverse . #f) 
                (node-values . #t) 
                (relative . #t)
            ) 
            (accuracy-control tolerance . 0.001) 
            (option 
                (oil-flow . #f) 
                (onzone) 
                (reverse . #f) 
                (node-values . #f) 
                (accuracy-controls . #f) 
                (step-size . 0.) 
                (tolerance . 0.) 
                (relative . #f) 
                (step . 0) 
                (skip . 0) 
                (coarsen . 0)
            ) 
            (step . 500) 
            (skip . 5) 
            (coarsen . 1) 
            (onzone) 
            (on-location (physics) (geometry) (surfaces)) 
            (plot 
                (enabled? . #f) 
                (x-axis-function . "") 
                (to-file-enabled? . #f) 
                (file-name . "")
            ) 
            (color-map 
                (visible? . #t) 
                (color . "field-velocity") 
                (size . 100) 
                (log-scale? . #f) 
                (format . "%0.2e") 
                (user-skip . 9) 
                (show-all . #t) 
                (position . 1) 
                (font-name . "Helvetica") 
                (font-automatic . #t) 
                (font-size . 0.032) 
                (length . 0.54) 
                (width . 6.) 
                (bground-transparent? . #t) 
                (bground-color . "#CCD3E2") 
                (title-elements . "Variable and Object Name")
            ) 
            (annotations-list) 
            (draw-mesh? . #f) 
            (mesh-object . "") 
            (display-state-name . "None") 
            (axes 
                (numbers 
                    (x-format . "") 
                    (x-axis-precision . 0) 
                    (y-format . "") 
                    (y-axis-precision . 0)
                ) 
                (rules 
                    (x-axis 
                        (draw-major-rules? . #f) 
                        (major-rule-weight . 0.) 
                        (major-rule-line-color . "") 
                        (automatic-major-rules? . #f) 
                        (major-rule-distance . 0.) 
                        (major-rule-divisions . 0.) 
                        (draw-minor-rules? . #f) 
                        (minor-rule-weight . 0.) 
                        (minor-rule-line-color . "") 
                        (automatic-minor-rules? . #f) 
                        (minor-rule-distance . 0.)
                    ) 
                    (y-axis 
                        (draw-major-rules? . #f) 
                        (major-rule-weight . 0.) 
                        (major-rule-line-color . "") 
                        (automatic-major-rules? . #f) 
                        (major-rule-distance . 0.) 
                        (major-rule-divisions . 0.) 
                        (draw-minor-rules? . #f) 
                        (minor-rule-weight . 0.) 
                        (minor-rule-line-color . "") 
                        (automatic-minor-rules? . #f) 
                        (minor-rule-distance . 0.)
                    )
                ) 
                (log-scale 
                    (x-axis? . #f) 
                    (y-axis? . #f)
                ) 
                (auto-scale 
                    (x-axis? . #f) 
                    (x-axis-min-auto? . #f) 
                    (x-axis-max-auto? . #f) 
                    (x-axis-min . 0.) 
                    (x-axis-max . 0.) 
                    (y-axis? . #f) 
                    (y-axis-min-auto? . #f) 
                    (y-axis-max-auto? . #f) 
                    (y-axis-min . 0.) 
                    (y-axis-max . 0.)
                ) 
                (labels 
                    (x-axis . "") 
                    (y-axis . "")
                )
            ) 
            (curves . #f)
        )
    )
)
