(graphics/vectors 
    (
        (
            (name . "vector-1")
            (vector-field . "velocity")
            (field . "velocity-magnitude")
            (surfaces-list 11)
            (location-ids)
            (locations (physics) (geometry) (surfaces))
            (range-option auto-range-on (global-range? . #t))
            (range-options 
                (global-range? . #f)
                (auto-range? . #f)
                (clip-to-range? . #f)
                (minimum . 0.)
                (maximum . 0.)
                (compute . #f)
            )
            (options 
                (auto-scale? . #f)
                (vector-style . "")
                (scale . 0.)
                (skip . 0)
            )
            (scale 
                (auto-scale? . #t)
                (scale-f . 0.02)
            )
            (style . "3d arrow")
            (skip . 3)
            (vector-opt 
                (in-plane? . #f)
                (fixed-length? . #t)
                (x-comp? . #t)
                (y-comp? . #t)
                (z-comp? . #t)
                (scale-head . 0.3)
                (tessellation . 24)
                (color . "")
            )
            (color-map 
                (visible? . #t)
                (color . "field-velocity")
                (size . 100)
                (log-scale? . #f)
                (format . "%0.2e")
                (user-skip . 9)
                (show-all . #t)
                (position . 1)
                (font-name . "Helvetica")
                (font-automatic . #t)
                (font-size . 0.032)
                (length . 0.54)
                (width . 6.)
                (bground-transparent? . #t)
                (bground-color . "#CCD3E2")
                (title-elements . "Variable and Object Name")
            )
            (annotations-list)
            (draw-mesh? . #f)
            (mesh-object . "")
            (display-state-name . "None")
        )
    )
)
