(graphics/xy-plot 
    (
        (
            (name . "xy-plot-1") 
            (uid . "uid-1") 
            (options 
                (node-values? . #t) 
                (position-on-x-axis? . #t) 
                (position-on-y-axis? . #f)
            ) 
            (y-axis-function . "pressure") 
            (x-axis-function . "Direction Vector") 
            (x-axis-data 
                (option . "") 
                (x-axis-direction 
                    (x-component . 0) 
                    (y-component . 0) 
                    (z-component . 0) 
                    (curve-length . "")
                ) 
                (x-axis-function . "")
            ) 
            (y-axis-data 
                (option . "") 
                (y-axis-direction 
                    (x-component . 0) 
                    (y-component . 0) 
                    (z-component . 0) 
                    (curve-length . "")
                ) 
                (y-axis-function . "")
            ) 
            (surfaces-list 0) 
            (location-ids) 
            (locations 
                (physics) 
                (geometry) 
                (surfaces)
            ) 
            (option 
                (node-values? . #f)
            ) 
            (plot-direction direction-vector 
                (x-component . 1.) 
                (y-component . 0.) 
                (z-component . 0.)
            ) 
            (axes 
                (numbers 
                    (x-format . "") 
                    (x-axis-precision . 0) 
                    (y-format . "") 
                    (y-axis-precision . 0)
                ) 
                (rules 
                    (x-axis 
                        (draw-major-rules? . #f)
                        (major-rule-weight . 0.) 
                        (major-rule-line-color . "") 
                        (automatic-major-rules? . #f) 
                        (major-rule-distance . 0.) 
                        (major-rule-divisions . 0.) 
                        (draw-minor-rules? . #f) 
                        (minor-rule-weight . 0.) 
                        (minor-rule-line-color . "") 
                        (automatic-minor-rules? . #f) 
                        (minor-rule-distance . 0.)
                    ) 
                    (y-axis 
                        (draw-major-rules? . #f) 
                        (major-rule-weight . 0.) 
                        (major-rule-line-color . "") 
                        (automatic-major-rules? . #f) 
                        (major-rule-distance . 0.) 
                        (major-rule-divisions . 0.) 
                        (draw-minor-rules? . #f) 
                        (minor-rule-weight . 0.) 
                        (minor-rule-line-color . "") 
                        (automatic-minor-rules? . #f) 
                        (minor-rule-distance . 0.)
                    )
                ) 
                (log-scale 
                    (x-axis? . #f) 
                    (y-axis? . #f)
                ) 
                (auto-scale 
                    (x-axis? . #f) 
                    (x-axis-min-auto? . #f) 
                    (x-axis-max-auto? . #f) 
                    (x-axis-min . 0.) 
                    (x-axis-max . 0.) 
                    (y-axis? . #f) 
                    (y-axis-min-auto? . #f) 
                    (y-axis-max-auto? . #f) 
                    (y-axis-min . 0.) 
                    (y-axis-max . 0.)
                ) 
                (labels 
                    (x-axis . "") 
                    (y-axis . "")
                )
            ) 
            (curves . #f)
        )
    )
)
