(graphics/contours 
    (
        (
            (name . "contour-3")
            (field . "pressure")
            (surfaces-list 11)
            (location-ids)
            (locations (physics) (geometry) (surfaces))
            (range-option auto-range-on (global-range? . #f))
            (range-options 
                (global-range? . #f)
                (auto-range? . #f)
                (clip-to-range? . #f)
                (minimum . 0.)
                (maximum . 0.)
                (compute . #f)
            )
            (options 
                (filled? . #f)
                (node-values? . #f)
                (boundary-values? . #f)
                (contour-lines? . #f)
            )
            (filled? . #t)
            (node-values? . #t)
            (boundary-values? . #t)
            (contour-lines? . #f)
            (coloring smooth . #t)
            (colorings (banded . #f) (smooth . #f))
            (color-map 
                (visible? . #t)
                (color . "field-velocity")
                (size . 100)
                (log-scale? . #f)
                (format . "%0.2e")
                (user-skip . 9)
                (show-all . #t)
                (position . 1)
                (font-name . "Helvetica")
                (font-automatic . #t)
                (font-size . 0.032)
                (length . 0.65)
                (width . 6.)
                (bground-transparent? . #t)
                (bground-color . "#CCD3E2")
                (title-elements . "Variable and Object Name")
            )
            (annotations-list)
            (draw-mesh? . #f)
            (mesh-object . "")
            (display-state-name . "None")
            (deformation? . #f)
            (deformation-scale . 1.)
        )
        (
            (name . "contour-2")
            (field . "pressure")
            (surfaces-list 11)
            (location-ids)
            (locations (physics) (geometry) (surfaces))
            (range-option auto-range-on (global-range? . #f))
            (range-options 
                (global-range? . #f)
                (auto-range? . #f)
                (clip-to-range? . #f)
                (minimum . 0.)
                (maximum . 0.)
                (compute . #f)
            )
            (options 
                (filled? . #f)
                (node-values? . #f)
                (boundary-values? . #f)
                (contour-lines? . #f)
            )
            (filled? . #t)
            (node-values? . #t)
            (boundary-values? . #t)
            (contour-lines? . #f)
            (coloring smooth . #t)
            (colorings (banded . #f) (smooth . #f))
            (color-map 
                (visible? . #t)
                (color . "field-velocity")
                (size . 100)
                (log-scale? . #f)
                (format . "%0.2e")
                (user-skip . 9)
                (show-all . #t)
                (position . 1)
                (font-name . "Helvetica")
                (font-automatic . #t)
                (font-size . 0.032)
                (length . 0.65)
                (width . 6.)
                (bground-transparent? . #t)
                (bground-color . "#CCD3E2")
                (title-elements . "Variable and Object Name")
            )
            (annotations-list)
            (draw-mesh? . #f)
            (mesh-object . "")
            (display-state-name . "None")
            (deformation? . #f)
            (deformation-scale . 1.)
        )
        (
            (name . "contour-1")
            (field . "temperature")
            (surfaces-list 11)
            (location-ids)
            (locations (physics) (geometry) (surfaces))
            (range-option auto-range-on (global-range? . #f))
            (range-options 
                (global-range? . #f)
                (auto-range? . #f)
                (clip-to-range? . #f)
                (minimum . 0.)
                (maximum . 0.)
                (compute . #f)
            )
            (options 
                (filled? . #f)
                (node-values? . #f)
                (boundary-values? . #f)
                (contour-lines? . #f)
            )
            (filled? . #t)
            (node-values? . #t)
            (boundary-values? . #t)
            (contour-lines? . #f)
            (coloring smooth . #t)
            (colorings (banded . #f) (smooth . #f))
            (color-map 
                (visible? . #t)
                (color . "field-velocity")
                (size . 100)
                (log-scale? . #f)
                (format . "%0.2e")
                (user-skip . 9)
                (show-all . #t)
                (position . 1)
                (font-name . "Helvetica")
                (font-automatic . #t)
                (font-size . 0.032)
                (length . 0.65)
                (width . 6.)
                (bground-transparent? . #t)
                (bground-color . "#1F1F1F")
                (title-elements . "Variable and Object Name")
            )
            (annotations-list)
            (draw-mesh? . #f)
            (mesh-object . "")
            (display-state-name . "None")
            (deformation? . #f)
            (deformation-scale . 1.)
        )
    )
)
