(monitor/monitorsets 
    (
        (
            (name . "key-params") 
            (old-props active? #t file-name ".\\key-params_30_1.out" frequency 1 frequency-of "iteration" report-defs ("temp_fluid_air" "temp_fluid_oil" "outlet_temp" "outlet_air_temp" "lv_heat" "outlet_tempurature") print? #f header "" report-frequency 1 flow-frequency 1 write-instantaneous-values? #f name "key-params" type "report-file") 
            (file-name . ".\\key-params.out") 
            (frequency . 1) 
            (flow-frequency . 1) 
            (itr-index . "1") 
            (run-index . "30") 
            (frequency-of . "iteration") 
            (report-defs "temp_fluid_air" "temp_fluid_oil" "outlet_temp" "outlet_air_temp" "lv_heat" "outlet_tempurature") 
            (print? . #f) 
            (active? . #t) 
            (write-instantaneous-values? . #f)
        ) 
        (
            (name . "total-heat-transfer-rfile") 
            (old-props active? #t file-name ".\\total-heat-transfer-rfile.out" frequency 1 frequency-of "iteration" report-defs () print? #t header "" report-frequency 1 flow-frequency 1 write-instantaneous-values? #f name "total-heat-transfer-rfile" type "report-file") 
            (file-name . ".\\total-heat-transfer-rfile.out") 
            (frequency . 1) 
            (flow-frequency . 1) 
            (itr-index . "1") 
            (run-index . "0") 
            (frequency-of . "iteration") 
            (report-defs) 
            (print? . #t) 
            (active? . #t) 
            (write-instantaneous-values? . #f)
        )
    )
)
