(named-expressions 
    (
        (
            (name . "density_air") 
            (definition . "1.110022907060436 [kg/m^3]") 
            (description . "") 
            (parameterid . "real-1") 
            (parametername . "density_air") 
            (unit . "density") 
            (input-parameter . #t) 
            (output-parameter . #f)
        ) 
        (
            (name . "th_lvinsu") 
            (definition . "0.2 [W/(m K)]") 
            (description . "") 
            (parameterid . "real-2") 
            (parametername . "th_lvinsu") 
            (unit . "thermal-conductivity") 
            (input-parameter . #t) 
            (output-parameter . #f)
        ) 
        (
            (name . "th_barr") 
            (definition . "0.2 [W/(m K)]") 
            (description . "") 
            (parameterid . "real-3") 
            (parametername . "th_barr") 
            (unit . "thermal-conductivity") 
            (input-parameter . #t) 
            (output-parameter . #f)
        ) 
        (
            (name . "th_epoxy") 
            (definition . "0.9 [W/(m K)]") 
            (description . "") 
            (parameterid . "real-4") 
            (parametername . "th_epoxy") 
            (unit . "thermal-conductivity") 
            (input-parameter . #t) 
            (output-parameter . #f)
        ) 
        (
            (name . "T_inlet") 
            (definition . "318.15 [K]") 
            (description . "") 
            (parameterid . "real-5") 
            (parametername . "T_inlet") 
            (unit . "temperature") 
            (input-parameter . #t) 
            (output-parameter . #f)
        ) 
        (
            (name . "rad_hv") 
            (definition . "0.95") 
            (description . "") 
            (parameterid . "real-6") 
            (parametername . "rad_hv") 
            (unit . "") 
            (input-parameter . #t) 
            (output-parameter . #f)
        ) 
        (
            (name . "rad_lv") 
            (definition . "0.9") 
            (description . "") 
            (parameterid . "real-7") 
            (parametername . "rad_lv") 
            (unit . "") 
            (input-parameter . #t) 
            (output-parameter . #f)
        ) 
        (
            (name . "rad_barr") 
            (definition . "0.9") 
            (description . "") 
            (parameterid . "real-8") 
            (parametername . "rad_barr") 
            (unit . "") 
            (input-parameter . #t) 
            (output-parameter . #f)
        ) 
        (
            (name . "rad_hv_ext") 
            (definition . "0.67") 
            (description . "") 
            (parameterid . "real-9") 
            (parametername . "rad_hv_ext") 
            (unit . "") 
            (input-parameter . #t) 
            (output-parameter . #f)
        ) 
        (
            (name . "tk_coreinsu") 
            (definition . "0.001 [m]") 
            (description . "") 
            (parameterid . "real-10") 
            (parametername . "tk_coreinsu") 
            (unit . "length") 
            (input-parameter . #t) 
            (output-parameter . #f)
        ) 
        (
            (name . "rad_core") 
            (definition . "0.9") 
            (description . "") 
            (parameterid . "real-11") 
            (parametername . "rad_core") 
            (unit . "") 
            (input-parameter . #t) 
            (output-parameter . #f)
        )
    )
)
