(monitor/plotsets 
    (
        (
            (name . "Monitor") 
            (plot-window . #f) 
            (old-props active? #t window-id 0 evaluate? #t frequency 1 frequency-of "iteration" report-defs ("outlet_tempurature") print? #f report-frequency 1 flow-frequency 1 name "Monitor" type "report-plot") 
            (frequency . 1) 
            (flow-frequency . 1) 
            (frequency-of . "iteration") 
            (report-defs "outlet_tempurature") 
            (print? . #f) 
            (title . "") 
            (x-label . "iteration") 
            (y-label . "Mass-Weighted Average of temperature") 
            (active? . #t) 
            (evaluate? . #t) 
            (plot-instantaneous-values? . #f)
        ) 
        (
            (name . "total-heat-trans") 
            (plot-window . #f) 
            (old-props active? #t window-id 1 evaluate? #t frequency 1 frequency-of "iteration" report-defs ("total heat trans") print? #f report-frequency 1 flow-frequency 1. name "total-heat-trans" type "report-plot") 
            (frequency . 1) 
            (flow-frequency . 1.) 
            (frequency-of . "iteration") 
            (report-defs "total heat trans") 
            (print? . #f) 
            (title . "total-heat-trans") 
            (x-label . "iteration") 
            (y-label . "Total Heat Transfer Rate") 
            (active? . #t) 
            (evaluate? . #t) 
            (plot-instantaneous-values? . #f)
        )
    )
)
