(sliding-interfaces 
    (
        (air-boundary 
            (sb1-id 293) 
            (sb2-id 1) 
            (interior-id 2) 
            (bnd1-id 0) 
            (bnd2-id 0) 
            (periodic . #f) 
            (coupled . #f) 
            (matching . #t) 
            (mapped . #f) 
            (static . #f) 
            (face-periodic . #t) 
            (turbo . #f) 
            (turbo-non-overlap . #f) 
            (no-ps . #f) 
            (stretched . #f) 
            (mixing . #f) 
            (phase-lag-sp . #f) 
            (stationary . #f) 
            (boundary-interface . #f) 
            (isect-cyl? . #f) 
            (phase-lag-fp . #f) 
            (phase-lag-fp-param) 
            (mperiodic-ids) 
            (sb1-str-id) 
            (sb2-str-id) 
            (mperiodic-str-ids) 
            (interior-str-id) 
            (bnd1-str-id) 
            (bnd2-str-id) 
            (cperiodic-id) 
            (cperiodic-str-id) 
            (bnd1-gti-id) 
            (bnd2-gti-id) 
            (mti1-id) 
            (mti2-id) 
            (nper . 0) 
            (nper-str . 0) 
            (mpm-avg . 1) 
            (mpm-bins . 40) 
            (nps-po-loss? . #f) 
            (flux-scale? . #t) 
            (one-to-one-pair) 
            (all-to-all-si-name) 
            (dynamic-sb-id) 
            (side-ws-avail . #f) 
            (side1-ws-avail . #f) 
            (side2-ws-avail . #f) 
            (side1-ws-ids) 
            (side2-ws-ids) 
            (x . 0.) 
            (y . 0.) 
            (z . -0.05399996566772461) 
            (side-switched . #f) 
            (mperiodic-angles)
        )
    )
)
