name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    name: Build & Create Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Extract Release Notes from CHANGELOG
        id: changelog_reader
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: query
          version: latest

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - name: Install build
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.changelog_reader.outputs.version && format('v{0}', steps.changelog_reader.outputs.version) || github.ref_name }}
          files: dist/*
          body: ${{ steps.changelog_reader.outputs.release-notes }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
